### ISSUE TITLE
weird behaviour

### ISSUE THREAD

**Issue by psychomad** [ReddyyZ/astsu#1]
Hello,
installed following the indications and the result is:

/usr/bin/astsu:63: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if protocol is "TCP":
/usr/bin/astsu:79: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "UDP":
/usr/bin/astsu:144: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if protocol is "TCP":
/usr/bin/astsu:146: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "UDP":
/usr/bin/astsu:187: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if protocol is "TCP" and stealth:
/usr/bin/astsu:189: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "TCP" and not stealth:
/usr/bin/astsu:191: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "UDP":
Traceback (most recent call last):
  File "/usr/bin/astsu", line 5, in <module>
    from scapy.all import *
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 18, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 56, in <module>
    from scapy.arch.linux import *  # noqa F403
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 29, in <module>
    from scapy.packet import Packet, Padding
  File "/usr/lib/python3/dist-packages/scapy/packet.py", line 29, in <module>
    from scapy.extlib import PYX
  File "/usr/lib/python3/dist-packages/scapy/extlib.py", line 21, in <module>
    from matplotlib import get_backend as matplotlib_get_backend
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 207, in <module>
    _check_versions()
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 202, in _check_versions
    if LooseVersion(module.__version__) < minver:
AttributeError: module 'numpy' has no attribute '__version__'

OS: Kali2020.2
Any hint?

**Comment by ReddyyZ** [comment]
Are you using Python 3?

**Comment by psychomad** [comment]
Yes python3 last update

**Comment by ReddyyZ** [comment]
Did you install all dependencies?

**Comment by psychomad** [comment]
installed and checked.
i did all as you wrote.. for this reason i don't understand the behaviour :)

**Comment by ReddyyZ** [comment]
I just tested on a new virtual machine and the warnings appear on it, but there is no error.
I have no idea why this error.

**Comment by psychomad** [comment]
neither i ... i will try to dig into and i will let you know. 
Thanks for the time
cya

**Comment by ReddyyZ** [comment]
Ok

**Comment by alexynior28** [comment]
Hello, I have the similar error in Windows 10.

![error](https://user-images.githubusercontent.com/19245743/83955893-83625900-a81d-11ea-9421-49799187fb4c.PNG)

```
astsu.py:63: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if protocol is "TCP":
astsu.py:79: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "UDP":
astsu.py:144: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if protocol is "TCP":
astsu.py:146: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "UDP":
astsu.py:187: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if protocol is "TCP" and stealth:
astsu.py:189: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "TCP" and not stealth:
astsu.py:191: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif protocol is "UDP":
```
By installing the dependencies you got the following.
```
Using legacy setup.py install for scapy, since package 'wheel' is not installed.
Using legacy setup.py install for nmap-vscan, since package 'wheel' is not installed.
Installing collected packages: scapy, nmap-vscan
    Running setup.py install for scapy ... done
    Running setup.py install for nmap-vscan ... done
Successfully installed nmap-vscan-1.1.0 scapy-2.4.3
```
so i installed it manually but got the same result

**Comment by ReddyyZ** [comment]
Ignore it, it's only a warning, i will resolve this on the next version.
Scans will still work.

**Comment by alexynior28** [comment]
Great, thanks
